[env:lilygo-lora32]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wshadow
    -Wconversion
    -Wdouble-promotion

lib_deps =
    jgromes/RadioLib @ ^7.7.1
    olikraus/U8g2 @ ^2.36.2

build_src_filter = 
    +<*>
    -<samples/>